server:
  port: 8081
spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: edrusthkebnu@gmail.com
    password: 119678ArKa37
    properties:
      mail:
        smtp:
          auth: true
        starttls:
          enable: true
help:
  recipient: bezlotangelo@gmail.com